version: "3.9"

services:
  flask_starter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_starter
    ports:
      - "5000:5000"
    environment:
      # IMPORTANT: This sets your SQLAlchemy DB URL
      - DB_URL=postgresql://flask_user:flask_password@postgres:5432/flask_db
      - FLASK_DEBUG=true
      - FLASK_APP=src/app.py
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    working_dir: /app
    command: ["poetry", "run", "flask", "run", "-h", "0.0.0.0", "-p", "5000"]
    mem_limit: 1g
    cpus: 0.5

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: flask_password
      POSTGRES_DB: flask_db
    ports:
      - "5432:5432"
